# Generated by Django 6.1.1 on 2026-09-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_main', models.BooleanField(default=False, verbose_name='المستثمر الرئيسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مساهم',
                'verbose_name_plural': 'المساهمون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=80, unique=True, verbose_name='معرف الأرض')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المساحة')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الشراء')),
                ('seller_name', models.CharField(max_length=150, verbose_name='البائع')),
                ('purchased_at', models.DateTimeField(verbose_name='تاريخ الشراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'أرض',
                'verbose_name_plural': 'الأراضي',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='اسم المشروع')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('planning', 'تخطيط'), ('building', 'قيد الإنشاء'), ('ready', 'جاهز للبيع'), ('sold', 'تم البيع'), ('closed', 'مغلق')], default='planning', max_length=20, verbose_name='الحالة')),
                ('main_investor_percentage', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='نسبة المستثمر الرئيسي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('land', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='core.land', verbose_name='الأرض')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قيمة المساهمة')),
                ('contribution_percentage', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='نسبة المساهمة')),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الربح المستحق')),
                ('distributed_at', models.DateTimeField(verbose_name='تاريخ التوزيع')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profit_distributions', to='core.investor', verbose_name='المساهم')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profit_distributions', to='core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'توزيع أرباح',
                'verbose_name_plural': 'توزيعات الأرباح',
                'ordering': ['-distributed_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('contribution', 'مساهمة'), ('profit', 'توزيع أرباح'), ('expense', 'مصروف'), ('sale', 'بيع')], max_length=20, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد قبل العملية')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد بعد العملية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.investor', verbose_name='المساهم')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'عملية مالية',
                'verbose_name_plural': 'العمليات المالية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100, verbose_name='نوع التكلفة')),
                ('beneficiary', models.CharField(max_length=150, verbose_name='المستفيد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('payment_method', models.CharField(max_length=60, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('operation_type', models.CharField(default='مساهمة', max_length=30, verbose_name='نوع العملية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='core.investor', verbose_name='المساهم')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مساهمة في مشروع',
                'verbose_name_plural': 'مساهمات المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='الوحدة')),
                ('buyer_name', models.CharField(max_length=150, verbose_name='المشتري')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر البيع')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المتبقي')),
                ('payment_method', models.CharField(max_length=60, verbose_name='طريقة الدفع')),
                ('sold_at', models.DateTimeField(verbose_name='تاريخ البيع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'عملية بيع',
                'verbose_name_plural': 'المبيعات',
                'ordering': ['-sold_at'],
            },
        ),
    ]
